spring:
  application:
    name: authService

  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: root
    password: root

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
